services:
  api:
    hostname: "studio-api"
    image: "prowler-studio-api"
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file:
      - path: ".env"
        required: false
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"

  ui:
    hostname: "studio-ui"
    image: "prowler-studio-ui"
    build:
      context: ui/
      dockerfile: Dockerfile
    env_file:
      - path: ".env"
        required: false
    ports:
      - "${UI_PORT:-80}:${UI_PORT:-80}"
