[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core"]

[tool.poetry]
authors = ["Prowler Team"]
description = ""
name = "prowler-studio"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
llama-index-core = "^0.11.22"
llama-index-llms-llama-cpp = "^0.2.3"
python = "^3.12"
safety = "^3.2.10"
