# Description: This file contains useful examples of how a check is created taking as reference some possible user queries related to cloud security.
EXAMPLE_CHECK_CREATION_WORKFLOW = {
    # AWS
    "make a check to ensure that the S3 bucket is not public.": {
        "security_analysis": "The requested prompt is related to cloud security, specifically with AWS because S3 is an AWS service for storage. This is a common security best practice to avoid unauthorized access to the bucket content.\nTo do this check you must verify at 4 levels: - Account level: verify that 'Block Public Access' is enabled for the account settings. - Bucket access permissions: verify each bucket has 'Block public access through ACLs' and 'Block public access through bucket policies' enabled. - Access control list (ACL): verify that the bucket does not have an ACL with 'AllUsers' or 'Authenticated Users' with 'List' or 'Write' permissions. - Bucket policy: verify that the bucket does not have a bucket policy that allows public access.",
        "prowler_provider": "aws",
        "service": "s3",
        "check_name": "s3_bucket_not_public_accesible",
        "check_metadata": r"{\n  'Provider': 'aws',\n  'CheckID': 's3_bucket_not_public_accesible',\n  'CheckTitle': 'Ensure there are no S3 buckets open to Everyone or Any AWS user.',\n  'CheckType': [\n\t'Data Protection'\n  ],\n  'ServiceName': 's3',\n  'SubServiceName': '',\n  'ResourceIdTemplate': 'arn:partition:s3:::bucket_name',\n  'Severity': 'critical',\n  'ResourceType': 'AwsS3Bucket',\n  'Description': 'Ensure there are no S3 buckets open to Everyone or Any AWS user.',\n  'Risk': 'Even if you enable all possible bucket ACL options available in the Amazon S3 console the ACL alone does not allow everyone to download objects from your bucket. Depending on which option you select any user could perform some actions.',\n  'RelatedUrl': '',\n  'Remediation': {\n\t'Code': {\n\t  'CLI': 'aws s3api put-public-access-block --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true --bucket <bucket_name>',\n\t  'NativeIaC': '',\n\t  'Other': '',\n\t  'Terraform': ''\n\t}\n  },\n  'Categories': [\n\t'internet-exposed'\n  ],\n  'DependsOn': [],\n  'RelatedTo': [],\n  'Notes': ''\n}",
    },
    # Azure
    "how can I ensure that my Entra policy is secure?": {
        "security_analysis": "The requested prompt is related to cloud security, specifically with Azure because Entra is the Microsoft product for identity and access management. This is a common security best practice to ensure that the Entra policy is secure to avoid unauthorized access to the resources.\nTo do this check at least you must verify that the Security Defaults are enabled.",
        "prowler_provider": "azure",
        "service": "entra",
        "check_name": "entra_security_defaults_enabled",
        "check_metadata": r"{\n  'Provider': 'azure',\n  'CheckID': 'entra_security_defaults_enabled',\n  'CheckTitle': 'Ensure Security Defaults is enabled on Microsoft Entra ID',\n  'CheckType': [],\n  'ServiceName': 'entra',\n  'SubServiceName': '',\n  'ResourceIdTemplate': '',\n  'Severity': 'high',\n  'ResourceType': '#microsoft.graph.identitySecurityDefaultsEnforcementPolicy',\n  'Description': 'Security defaults in Microsoft Entra ID make it easier to be secure and help protect your organization. Security defaults contain preconfigured security settings for common attacks. Security defaults is available to everyone. The goal is to ensure that all organizations have a basic level of security enabled at no extra cost. You may turn on security defaults in the Azure portal.',\n  'Risk': 'Security defaults provide secure default settings that we manage on behalf of organizations to keep customers safe until they are ready to manage their own identity security settings. For example, doing the following: - Requiring all users and admins to register for MFA. - Challenging users with MFA - when necessary, based on factors such as location, device, role, and task. - Disabling authentication from legacy authentication clients, which cant do MFA.',\n  'RelatedUrl': '',\n  'Remediation': {\n\t'Code': {\n\t  'CLI': '',\n\t  'NativeIaC': '',\n\t  'Other': '',\n\t  'Terraform': ''\n\t},\n\t'Recommendation': {\n\t  'Text': '1. From Azure Home select the Portal Menu. 2. Browse to Microsoft Entra ID > Properties 3. Select Manage security defaults 4. Set the Enable security defaults to Enabled 5. Select Save',\n\t  'Url': ''\n\t}\n  },\n  'Categories': [],\n  'DependsOn': [],\n  'RelatedTo': [],\n  'Notes': 'This recommendation should be implemented initially and then may be overridden by other service/product specific CIS Benchmarks. Administrators should also be aware that certain configurations in Microsoft Entra ID may impact other Microsoft services such as Microsoft 365.'\n}",
    },
    # GCP
    "create a check to ensure BigQuery datasets are encrypted with Customer-Managed Keys (CMKs).": {
        "security_analysis": "The requested prompt is related to cloud security, specifically with GCP because BigQuery is a GCP product for data analysis. This is a common security best practice to ensure that the BigQuery datasets are encrypted with Customer-Managed Keys (CMKs) to avoid unauthorized access to the data.\nTo do this check you must verify that the BigQuery datasets are encrypted with Customer-Managed Keys (CMKs).",
        "prowler_provider": "gcp",
        "service": "bigquery",
        "check_name": "bigquery_dataset_cmk_encryption",
        "check_metadata": r"{\n  'Provider': 'gcp',\n  'CheckID': 'bigquery_dataset_cmk_encryption',\n  'CheckTitle': 'Ensure BigQuery datasets are encrypted with Customer-Managed Keys (CMKs).',\n  'CheckType': [],\n  'ServiceName': 'bigquery',\n  'SubServiceName': '',\n  'ResourceIdTemplate': '',\n  'Severity': 'high',\n  'ResourceType': 'Dataset',\n  'Description': 'Ensure BigQuery datasets are encrypted with Customer-Managed Keys (CMKs) in order to have a more granular control over data encryption/decryption process.',\n  'Risk': 'If you want to have greater control, Customer-managed encryption keys (CMEK) can be used as encryption key management solution for BigQuery Data Sets.',\n  'RelatedUrl': '',\n  'Remediation': {\n\t'Code': {\n\t  'CLI': ''\n\t}\n  },\n  'Categories': [\n\t'encryption'\n  ],\n  'DependsOn': [],\n  'RelatedTo': [],\n  'Notes': ''\n}",
    },
    # Kubernetes
    "create a check to ensure that in my k8s cluster the secrets are not stored in the environment variables.": {
        "security_analysis": "The requested prompt is related to cloud security, specifically with Kubernetes because k8s is the short name for Kubernetes. This is a common security best practice to avoid storing secrets in the environment variables to avoid unauthorized access to the secrets.\nTo do this check you must verify that the secrets are not stored in the environment variables, instead the best practice is mounting secrets as files for enhanced security.",
        "prowler_provider": "kubernetes",
        "service": "core",
        "check_name": "core_no_secrets_envs",
        "check_metadata": r"{\n  'Provider': 'kubernetes',\n  'CheckID': 'core_no_secrets_envs',\n  'CheckTitle': 'Prefer using secrets as files over secrets as environment variables',\n  'CheckType': [],\n  'ServiceName': 'core',\n  'SubServiceName': '',\n  'ResourceIdTemplate': '',\n  'Severity': 'medium',\n  'ResourceType': 'KubernetesSecrets',\n  'Description': 'This check ensures that secrets in Kubernetes are used as files rather than environment variables. Using secrets as files is safer, as it reduces the risk of exposing sensitive data through application logs.',\n  'Risk': 'Secrets exposed as environment variables can be inadvertently logged by applications, leading to potential security breaches.',\n  'RelatedUrl': '',\n  'Remediation': {\n\t'Code': {\n\t  'CLI': '',\n\t  'NativeIaC': '',\n\t  'Other': '',\n\t  'Terraform': ''\n\t},\n\t'Recommendation': {\n\t  'Text': 'Minimize the use of environment variable secrets and prefer mounting secrets as files for enhanced security.',\n\t  'Url': ''\n\t}\n  },\n  'Categories': [\n\t'trustboundaries'\n  ],\n  'DependsOn': [],\n  'RelatedTo': [],\n  'Notes': 'Mounting secrets as files allows for dynamic updates of secrets without needing to restart the pod.'\n}",
    },
}
